export enum DynamicIndicator {
  populationAffected = 'population_affected',
  populationAffectedPercentage = 'population_affected_percentage',
  potentialCasesU9 = 'potential_cases_U9',
  potentialCasesU5 = 'potential_cases_U5',
  potentialCases65 = 'potential_cases_65',
  alertThreshold = 'alert_threshold',
  potentialCases = 'potential_cases',
  potentialThreshold = 'potential_cases_threshold',
  ipcForecastShort = 'IPC_forecast_short',
  ipcForecastLong = 'IPC_forecast_long',
  hotspotGeneral = 'Hotspot_General',
  hotspotWater = 'Hotspot_Water',
  hotspotHealth = 'Hotspot_Health',
  cattleExposed = 'cattle_exposed',
  smallRuminantsExposed = 'small_ruminants_exposed',
  windspeed = 'windspeed',
  rainfall = 'rainfall',
  housesAffected = 'houses_affected',
  probabilisticHousesAffected = 'probabilistic_houses_affected',
}
