# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      root:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/services/API-service'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      backend-nestjs:
        patterns:
          - '@nestjs/*'
      backend-development:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
      backend:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/interfaces/IBF-dashboard'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      frontend-angular:
        patterns:
          - '@angular/*'
          - '@bluehalo/*'
          - 'angular-eslint'
          - '@angular-eslint/*'
          - '@angular-devkit/*'
          - 'zone.js'
      frontend-turf:
        patterns:
          - '@turf*'
      frontend-typescript:
        patterns:
          - 'typescript*'
      frontend-development:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
      frontend:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/tests/integration'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      integration-jest:
        patterns:
          - '*jest*'
      integration-development:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
      integration:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/tests/e2e'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      e2e-development:
        patterns:
          - '@types/*'
          - 'eslint*'
          - 'prettier*'
      e2e:
        patterns:
          - '*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
