# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/services/API-service'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      development:
        patterns:
          - '@types/*'
          - '*eslint*'
          - '*prettier*'
      nestjs:
        patterns: ['@nestjs/*']
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/interfaces/IBF-dashboard'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      angular:
        patterns:
          - '@angular*'
          - '@bluehalo/*'
          - 'zone.js'
      turf:
        patterns:
          - '@turf*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/tests/integration'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      development:
        patterns:
          - '@types/*'
          - '*eslint*'
          - '*prettier*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: '/tests/e2e'
    open-pull-requests-limit: 3
    schedule:
      interval: 'weekly'
    groups:
      development:
        patterns:
          - '@types/*'
          - '*eslint*'
          - '*prettier*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
