services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./tools/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./interfaces/IBF-dashboard/www/browser:/var/www/ibf-dashboard
    networks:
      - api-network
    restart: unless-stopped

  ibf-api-service:
    command: ['npm', 'run', 'start']
    environment:
      - NODE_ENV=ci
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - 3000:3000
    volumes: !override
      - ibf-api-service-node-modules:/home/ibf/api-service/node_modules
    depends_on:
      - ibf-local-db
    networks:
      - api-network

  ibf-local-db:
    image: postgis/postgis
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./tools/db-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5437:5432
    networks:
      - api-network
    restart: unless-stopped
