// a domain is mapped to a list of countries
// if a user from any listed domain registers
// they will be assigned to the listed countries
// sources:
// 1. https://www.ifrc.org/national-societies-directory
// 2. https://en.wikipedia.org/wiki/List_of_Red_Cross_and_Red_Crescent_societies

export default {
  '@redcross.org.zm': ['ZMB'],
  '@redcross.org.ls': ['LSO'],
  '@redcrossug.org': ['UGA'],
  '@redcrosszim.org.zw': ['ZWE'],
  '@redcross.or.ke': ['KEN'],
  '@redcross.org.ph': ['PHL'],
  '@redcrosseth.org': ['ETH'],
  '@redcross.mw': ['MWI'],
  '@ssdredcross.org': ['SSD'],
  '@cruzvermelha.og.ao': ['AGO'],
  '@croixrouge.bi': ['BDI'],
  '@croixrougebenin.org': ['BEN'],
  '@croix-rouge.bf': ['BFA'],
  '@botswanaredcross.org.bw': ['BWA'],
  '@croix-rougecentrafrique.org': ['CAF'],
  '@croix-rougeci.org': ['CIV'],
  '@croixrouge.cm': ['CMR'],
  '@croixrouge-rdc.org': ['COD'],
  '@crccongo-bzv.org': ['COG'],
  '@cr-comorien.org': ['COM'],
  '@cruzvermelha.org.cv': ['CPV'],
  '@croissantrouge-djib.org': ['DJI'],
  '@cra.dz': ['DZA'],
  '@egyptianrc.org': ['EGY'],
  // '': ['ERI'],
  '@croixrougegabon.org': ['GAB'],
  '@redcrossghana.org': ['GHA'],
  // '': ['GIN'],
  '@redcross.gm': ['GMB'],
  // '': ['GNB'],
  // '': ['GNQ'],
  '@lnrcs.org.lr': ['LBR'],
  '@lrc.org.ly': ['LBY'],
  '@croissant-rouge.ma': ['MAR'],
  '@crmada.org': ['MDG'],
  '@croix-rouge.ml': ['MLI'],
  '@redcross.org.mz': ['MOZ'],
  // '': ['MRT'],
  '@mauritiusredcross.org': ['MUS'],
  '@redcross.org.na': ['NAM'],
  '@croix-rouge.ne': ['NER'],
  '@redcrossnigeria.org': ['NGA'],
  '@rwandaredcross.org': ['RWA'],
  '@srcs.sd': ['SDN'],
  '@croix-rouge.sn': ['SEN'],
  '@sierraleoneredcross.org': ['SLE'],
  '@crucearosie.ro': ['SOM'],
  '@cruzvermelha-stop.org': ['STP'],
  '@redcross.org.sz': ['SWZ'],
  '@seychellesredcross.sc': ['SYC'],
  '@croixrougedutchad.org': ['TCD'],
  '@croixrouge-togo.org': ['TGO'],
  '@croissant-rouge.tn': ['TUN'],
  '@trcs.or.tz': ['TZA'],
  '@redcross.org.za': ['ZAF'],
};
