export enum AnalyticsPage {
  activationLog = 'activation-Log',
  dashboard = 'dashboard',
  login = 'login',
}

export enum AnalyticsEvent {
  aboutIbf = 'about-ibf',
  aboutTrigger = 'about-trigger',
  adminLevel = 'admin-level',
  aggregateInformation = 'aggregate-information',
  communityNotification = 'community-notification',
  dam = 'dam',
  documentation = 'documentation',
  download = 'download',
  eapAction = 'eap-action',
  evacuationCenter = 'evacuation-center',
  exportView = 'export-view',
  glofasStation = 'glofas-station',
  healthSite = 'health-site',
  leadTime = 'lead-time',
  loginChange = 'login-change',
  loginCode = 'login-code',
  loginEmail = 'login',
  loginReenter = 'login-reenter',
  loginResend = 'login-resend',
  logOut = 'log-out',
  mapLayer = 'map-layer',
  mapLayerInformation = 'map-layer-information',
  mapMarker = 'map-marker',
  mapPlaceSelect = 'map-place-select',
  redCrossBranch = 'red-cross-branch',
  riverGauge = 'river-gauge',
  school = 'school',
  setTrigger = 'set-trigger',
  support = 'support',
  typhoonTrack = 'typhoon-track',
  upload = 'upload',
  uploadFile = 'upload-file',
  watchIbfGuide = 'watch-ibf-guide',
  waterPoint = 'water-point',
}
