export enum AnalyticsPage {
  activationLog = 'activation-Log',
  dashboard = 'dashboard',
  login = 'login',
}

export enum AnalyticsEvent {
  aboutTrigger = 'about-trigger',
  adminLevel = 'admin-level',
  aggregateInformation = 'aggregate-information',
  communityNotification = 'community-notification',
  dam = 'dam',
  eapAction = 'eap-action',
  eapSubmit = 'eap-submit',
  evacuationCenter = 'evacuation-center',
  exportView = 'export-view',
  glofasStation = 'glofas-station',
  healthSite = 'health-site',
  leadTime = 'lead-time',
  logOut = 'log-out',
  mapLayer = 'map-layer',
  mapLayerInformation = 'map-layer-information',
  mapMarker = 'map-marker',
  mapPlaceSelect = 'map-place-select',
  redCrossBranch = 'red-cross-branch',
  riverGauge = 'river-gauge',
  school = 'school',
  setTrigger = 'set-trigger',
  typhoonTrack = 'typhoon-track',
  watchIbfGuide = 'watch-ibf-guide',
  waterPoint = 'water-point',
}
