name: 'integration'
description: 'Run integration tests'

inputs:
  twilio-sid:
    description: 'Twilio SID'
    required: true
  twilio-authtoken:
    description: 'Twilio AuthToken'
    required: true
  smtp-host:
    description: 'SMTP host'
    required: true
  smtp-port:
    description: 'SMTP port'
    required: true
  smtp-secure:
    description: 'SMTP secure (true/false)'
    required: true
  smtp-username:
    description: 'SMTP username'
    required: true
  smtp-password:
    description: 'SMTP password'
    required: true
  smtp-from:
    description: 'SMTP from address'
    required: true

runs:
  using: composite

  steps:
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version-file: './tests/integration/.node-version'
        cache: 'npm'
        cache-dependency-path: './tests/integration/package-lock.json'

    - name: Install code-dependencies
      shell: bash
      working-directory: ./tests/integration
      run: npm ci --omit=optional --no-fund --no-audit

    - name: Setup environment variables
      shell: bash
      run: cp example.env .env

    - name: Run IBF API-service
      shell: bash
      env:
        TWILIO_SID: ${{ inputs.twilio-sid }}
        TWILIO_AUTHTOKEN: ${{ inputs.twilio-authtoken }}
        SMTP_HOST: ${{ inputs.smtp-host }}
        SMTP_PORT: ${{ inputs.smtp-port }}
        SMTP_SECURE: ${{ inputs.smtp-secure }}
        SMTP_USERNAME: ${{ inputs.smtp-username }}
        SMTP_PASSWORD: ${{ inputs.smtp-password }}
        SMTP_FROM: ${{ inputs.smtp-from }}
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d ibf-api-service

    - name: Wait for IBF API-service to be running
      shell: bash
      run: timeout 90s sh -c 'until curl http://localhost:3000/api -I; do echo "Waiting for the IBF API-service to be running..."; sleep 1; done'

    - name: Run integration tests
      shell: bash
      working-directory: ./tests/integration
      env:
        DASHBOARD_URL: http://localhost:4200
      run: npm run test

    - name: Docker logs
      if: always()
      uses: jwalton/gh-docker-logs@v2
