export default {
    pageTitle: "[data-test='page-title']",
    inputUser: "[data-test='input-user'] input",
    inputPassword: "[data-test='input-password'] input",
    inputSubmit: "[data-test='login-button']",
    logOut: "[data-test='logout-button']",
    userDisplayNameLabel: "[data-test='user-display-name-label']",
    userDisplayName: "[data-test='user-display-name']",
    exportViewButton: "[data-test='export-view-button']",
    exportViewPopover: "[data-test='export-view-popover']",
    logoImage: "[data-test='logo-image']",
    loader: "[data-test='loader']",
    videoGuide: "[data-test=video-guide-button]",
    ActiveleadTimeButtons : "//*[starts-with(@class,'active')]",
    TotalPopulationName: "//*[starts-with(@class,'aggregate-item-label')][contains(text(),'Total')]",
    ExposedPopulationName: "//*[starts-with(@class,'aggregate-item-label')][contains(text(),'Expose')]",
    exposedPopulationNumber : "//*[starts-with(@title,'Exposed population')]//following::span[1]",
    TotalPopulationNumber : "//*[starts-with(@title,'Exposed population')]//following::span[2]",
  };
