export default {
  timeline: {
    timelineButton: '[data-test=timeline-button]',
    timelineButtonActive: '[data-test=timeline-button].active',
  },
  pageTitle: "[data-test='page-title']",
  inputUser: "[data-test='input-user'] input",
  inputPassword: "[data-test='input-password'] input",
  inputSubmit: "[data-test='login-button']",
  logOut: "[data-test='logout-button']",
  userDisplayNameLabel: "[data-test='user-display-name-label']",
  userDisplayName: "[data-test='user-display-name']",
  exportViewButton: "[data-test='export-view-button']",
  exportViewPopover: "[data-test='export-view-popover']",
  logoImage: "[data-test='logo-image']",
  loader: "[data-test='loader']",
  videoGuidebutton: '[data-test=video-guide-button]',
  videoGuideclosebutton: '[data-test=video-popover] .icon-large',
  aggregateList: '[data-test=aggregate-list]',
  aggregateNumber: '[data-test=aggregate-number]',
  ExposedaggregateNumber: ':nth-child(1)>>>[data-test=aggregate-number]',
  TotalaggregateNumber: ':nth-child(2)>>>[data-test=aggregate-number]',
  AggregatePopupicon: ':nth-child(1)>>[data-test=icon-row]',
  disastertypes: '[data-test=disaster-Type]',
  disasterlabel: '[data-test=disaster-labelname]',
  chat: '[data-test=chat]',
  aggregateTitle: '[data-test=aggregate-title]',
  AboutTrigger: '[data-test=chat-about-trigger]',
  layersOverview: '[data-test=layers-toggle]',
  layermenu: '[data-test=layers-control-menu]',
  matrixicon: '[data-test=matrix-icon]',
  layerpopupmessage: '[data-test=matrix-popupinfo]',
  layersPopupcloseIcon: '[data-test=close-matrix-icon]',
  mapoverview: '[data-test=leaflet-map]',
  ActionSummaryTitle: '[data-test=action-title]',
  ActionSummarytype: '[data-test=action-summary-types]',
  triggerActiveTrue: "[data-test='trigger-active-true']",
  triggerActiveFalse: "[data-test='trigger-active-false']",
};
