#!/usr/bin/env bash
#
# git hook to run a command before actually committing when running `git commit`:
#

ORANGE='\033[0;33m'
NC='\033[0m' # No Color

log() {
  printf "${ORANGE}[pre-commit]${NC} $1\n"
}

log "Running custom pre-commit hook defined in ./husky/pre-commit"

# Prevent committing to "main"-branch:
if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
  log "You shouldn't commit directly to the master branch."
  log "Create a feature branch:  git branch new-branch-name"
  log "Then reset 'master':        git reset --hard origin/master"
  log "And continue to work:     git checkout new-branch-name"
  exit 1
fi

log "Running lint-staged"
npx lint-staged

log "All done"
