name: 'e2e'
description: 'Run end-to-end tests'

inputs:
  twilio-sid:
    description: 'Twilio SID'
    required: true
  twilio-authtoken:
    description: 'Twilio AuthToken'
    required: true
  smtp-host:
    description: 'SMTP host'
    required: true
  smtp-port:
    description: 'SMTP port'
    required: true
  smtp-secure:
    description: 'SMTP secure (true/false)'
    required: true
  smtp-username:
    description: 'SMTP username'
    required: true
  smtp-password:
    description: 'SMTP password'
    required: true
  smtp-from:
    description: 'SMTP from address'
    required: true
  support-email-address:
    description: 'Support email address'
    required: true
  azure-dev-url:
    description: 'Azure DevOps URL'
    required: true
  azure-devops-token:
    description: 'Azure DevOps token'
    required: true
  azure-test-owner:
    description: 'Azure test owner'
    required: true

runs:
  using: composite

  steps:
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version-file: './tests/e2e/.node-version'
        cache: 'npm'
        cache-dependency-path: './tests/e2e/package-lock.json'

    - name: Install e2e code-dependencies
      shell: bash
      working-directory: ./tests/e2e
      run: npm ci --omit=optional --no-fund --no-audit

    - name: Lint e2e code
      shell: bash
      working-directory: ./tests/e2e
      run: npm run lint

    - name: Setup environment variables
      shell: bash
      run: cp example.env .env

    - name: Install IBF API-service code-dependencies
      shell: bash
      working-directory: ./services/API-service
      run: npm ci --omit=optional --no-fund --no-audit

    - name: Run IBF API-service and IBF Geoserver
      shell: bash
      env:
        TWILIO_SID: ${{ inputs.twilio-sid }}
        TWILIO_AUTHTOKEN: ${{ inputs.twilio-authtoken }}
        SMTP_HOST: ${{ inputs.smtp-host }}
        SMTP_PORT: ${{ inputs.smtp-port }}
        SMTP_SECURE: ${{ inputs.smtp-secure }}
        SMTP_USERNAME: ${{ inputs.smtp-username }}
        SMTP_PASSWORD: ${{ inputs.smtp-password }}
        SMTP_FROM: ${{ inputs.smtp-from }}
        SUPPORT_EMAIL_ADDRESS: ${{ inputs.support-email-address }}
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml up -d ibf-api-service ibf-geoserver

    - name: Start IBF dashboard
      shell: bash
      working-directory: 'interfaces/IBF-dashboard'
      env:
        API_SERVICE_URL: http://localhost:3000/api
        NG_CONFIGURATION: production
        NG_GEOSERVER_URL: http://localhost:8081/geoserver/ibf-system/wms
      run: |
        npm install
        npm run start:prod > dashboard-logs.txt 2>&1 &

    - name: Install runtime dependencies
      shell: bash
      working-directory: ./tests/e2e
      run: npx playwright install chromium --with-deps

    - name: Wait for IBF API-service to be running
      shell: bash
      run: timeout 60s sh -c 'until curl http://localhost:3000/api -I; do echo "Waiting for the IBF API-service to be running..."; sleep 1; done'

    - name: Wait for IBF dashboard to be running
      shell: bash
      run: timeout 60s sh -c 'until curl http://localhost:4200 -I; do echo "Waiting for the IBF dashboard to be running..."; sleep 1; done'

    - name: Run end-to-end tests
      shell: bash
      working-directory: ./tests/e2e
      env:
        DASHBOARD_URL: http://localhost:4200
        AZURE_DEV_URL: ${{ inputs.azure-dev-url }}
        AZURE_DEVOPS_TOKEN: ${{ inputs.azure-devops-token }}
        AZURE_TEST_OWNER: ${{ inputs.azure-test-owner }}
      run: npm test

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-result-artifacts
        path: |
          ./tests/e2e/test-results/
          ./interfaces/IBF-dashboard/dashboard-logs.txt
        retention-days: 30

    - name: Docker logs
      if: always()
      uses: jwalton/gh-docker-logs@v2
