# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test: E2E (IBF-System)'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/test_e2e_ibf_system.yml'
      - 'e2e/**'
      - './.env.example'
      - '!**.md'

env:
  e2eTestsPath: './e2e'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: '${{ env.e2eTestsPath }}/.node-version'
          cache: 'npm'
          cache-dependency-path: '${{ env.e2eTestsPath }}/package-lock.json'

      - name: Install E2E-Tests code-dependencies
        working-directory: ${{ env.e2eTestsPath }}
        run: |
          npm ci --omit=optional --no-fund --no-audit

      - name: Lint E2E-Tests code
        working-directory: ${{ env.e2eTestsPath }}
        run: 'npm run lint'

      - name: Set ENV-variables for test-environment
        run: |
          pwd
          cp env.example .env

      - name: Run Services with Docker
        working-directory: ./
        run: |
          docker --log-level 'warn' compose -f docker-compose.yml up -d --quiet-pull --wait --wait-timeout 300

      - name: Start Interface
        working-directory: ./
        env:
          NG_API_URL: http://localhost:4000/api
        run: |
          npm run start:interface

      - name: Install E2E-Tests runtime-dependencies
        working-directory: ${{ env.e2eTestsPath }}
        run: |
          npx playwright install chromium --with-deps

      - name: Wait for IBF-System to be running
        run: |
          timeout 90s sh -c 'until curl http://localhost:4200 -I; do echo "Waiting for the IBF-portal to be running..."; sleep 1; done'

      - name: Run E2E-Tests with Playwright
        working-directory: ${{ env.e2eTestsPath }}
        env:
          BASE_URL: http://localhost:4200
        run: |
          npm test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-result-artifacts
          path: |
            ${{ env.e2eTestsPath }}/test-results/
            ./interfaces/IBF-dashboard/ibf-server-logs.txt
          retention-days: 30

      - name: Docker logs
        if: always()
        uses: jwalton/gh-docker-logs@v2
