name: 'Run checks on pull request'

on:
  pull_request:

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      ibf-api-service: ${{ steps.filter.outputs.ibf-api-service }}
      ibf-dashboard: ${{ steps.filter.outputs.ibf-dashboard }}
      ibf-e2e: ${{ steps.filter.outputs.ibf-e2e }}
      ibf-integration: ${{ steps.filter.outputs.ibf-integration }}

    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ibf-api-service:
              - "services/API-service/**"
            ibf-dashboard:
              - "interfaces/IBF-dashboard/**"
            ibf-e2e:
              - "tests/e2e/**"
            ibf-integration:
              - "tests/integration/**"

  ibf-api-service:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ibf-api-service == 'true' }}

    runs-on: ubuntu-latest

    env:
      SECRET: ${{ secrets.SECRET }}
      MC_API: ${{ secrets.MC_API }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}

    defaults:
      run:
        working-directory: 'services/API-service'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: './services/API-service/.node-version'
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm test

  ibf-dashboard:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ibf-dashboard == 'true' }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'interfaces/IBF-dashboard'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: './interfaces/IBF-dashboard/.node-version'
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm run build
      - run: npm test

  ibf-integration:
    needs: detect-changes
    if: ${{
      needs.detect-changes.outputs.ibf-api-service == 'true' ||
      needs.detect-changes.outputs.ibf-integration == 'true'
      }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run integration test action
        uses: ./.github/actions/integration
        with:
          mailchimp-api-key: ${{ secrets.MC_API }}
          twilio-sid: ${{ secrets.TWILIO_SID }}
          twilio-authtoken: ${{ secrets.TWILIO_AUTHTOKEN }}

  ibf-e2e:
    needs: detect-changes
    if: ${{
      needs.detect-changes.outputs.ibf-api-service == 'true' ||
      needs.detect-changes.outputs.ibf-dashboard == 'true' ||
      needs.detect-changes.outputs.ibf-e2e == 'true'
      }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run e2e test action
        uses: ./.github/actions/e2e
        with:
          mailchimp-api-key: ${{ secrets.MC_API }}
