name: 'Run checks on pull request'

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  detect-changes:
    runs-on: ubuntu-latest

    outputs:
      ibf-api-service: ${{ steps.filter.outputs.ibf-api-service }}
      ibf-dashboard: ${{ steps.filter.outputs.ibf-dashboard }}
      ibf-e2e: ${{ steps.filter.outputs.ibf-e2e }}
      ibf-integration: ${{ steps.filter.outputs.ibf-integration }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ibf-api-service:
              - "services/API-service/**"
            ibf-dashboard:
              - "interfaces/IBF-dashboard/**"
            ibf-e2e:
              - "tests/e2e/**"
            ibf-integration:
              - "tests/integration/**"

  ibf-api-service:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ibf-api-service == 'true' }}

    runs-on: ubuntu-latest

    env:
      SECRET: ${{ secrets.SECRET }}
      TWILIO_SID: ${{ secrets.TWILIO_SID }}
      TWILIO_AUTHTOKEN: ${{ secrets.TWILIO_AUTHTOKEN }}
      SMTP_HOST: ${{ vars.SMTP_HOST }}
      SMTP_PORT: ${{ vars.SMTP_PORT }}
      SMTP_SECURE: ${{ vars.SMTP_SECURE }}
      SMTP_USERNAME: ${{ vars.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      SMTP_FROM: ${{ vars.SMTP_FROM }}

    defaults:
      run:
        working-directory: 'services/API-service'

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js version
        uses: actions/setup-node@v5
        with:
          node-version-file: './services/API-service/.node-version'
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm test

  ibf-dashboard:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.ibf-dashboard == 'true' }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'interfaces/IBF-dashboard'

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js version
        uses: actions/setup-node@v5
        with:
          node-version-file: './interfaces/IBF-dashboard/.node-version'
      - run: npm ci --no-audit
      - run: npm run lint
      - run: npm run build
      - run: npm test

  ibf-integration:
    needs: detect-changes
    if: ${{
      (needs.detect-changes.outputs.ibf-api-service == 'true'
      || needs.detect-changes.outputs.ibf-integration == 'true')
      && !github.event.pull_request.draft
      }}

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Run integration test action
        uses: ./.github/actions/integration
        with:
          twilio-sid: ${{ secrets.TWILIO_SID }}
          twilio-authtoken: ${{ secrets.TWILIO_AUTHTOKEN }}
          smtp-host: ${{ vars.SMTP_HOST }}
          smtp-port: ${{ vars.SMTP_PORT }}
          smtp-secure: ${{ vars.SMTP_SECURE }}
          smtp-username: ${{ vars.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          smtp-from: ${{ vars.SMTP_FROM }}

  ibf-e2e:
    needs: detect-changes
    if: ${{
      (needs.detect-changes.outputs.ibf-api-service == 'true'
      || needs.detect-changes.outputs.ibf-dashboard == 'true'
      || needs.detect-changes.outputs.ibf-e2e == 'true')
      && !github.event.pull_request.draft
      }}

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Run e2e test action
        uses: ./.github/actions/e2e
        with:
          azure-dev-url: ${{ vars.AZURE_DEV_URL }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-test-owner: ${{ vars.AZURE_TEST_OWNER }}
          smtp-host: ${{ vars.SMTP_HOST }}
          smtp-port: ${{ vars.SMTP_PORT }}
          smtp-secure: ${{ vars.SMTP_SECURE }}
          smtp-username: ${{ vars.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          smtp-from: ${{ vars.SMTP_FROM }}
